name: Bug Report
description: Report a reproducible bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please make sure this isn’t a duplicate before submitting.
  - type: input
    id: summary
    attributes:
      label: Bug Summary
      placeholder: Short summary of the issue
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Run '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
  - type: input
    id: environment
    attributes:
      label: Environment Details
      placeholder: OS, browser, or version info
